Files-HW was made
Sazan4ek/Laravel-php pull request #10
Opened 2024-03-09 09:55 UTC by Sazan4ek

2024-03-13 17:19 UTC, FilipovskyAlex requested changes

2024-03-13 17:19 UTC, FilipovskyAlex commented on Files-HW/app/Console/Commands/DeleteOldFiles.php
> +        foreach($oldFiles as $file)
здесь можно оптимизировать данную команду по очистке. Сможешь сам понять как?

2024-03-16 20:50 UTC, Sazan4ek commented on Files-HW/app/Console/Commands/DeleteOldFiles.php
> +        foreach($oldFiles as $file)
написал в тг

2024-03-18 06:21 UTC, FilipovskyAlex requested changes

2024-03-18 06:21 UTC, FilipovskyAlex commented on Files-HW/app/Console/Commands/DeleteOldFiles.php
> +        foreach($oldFiles as $file)
ответил в тг

2024-03-18 08:26 UTC, FilipovskyAlex approved these changes

2024-03-18 08:26 UTC, merged