Artisan-HW
Sazan4ek/Laravel-php pull request #11
Opened 2024-03-16 16:15 UTC by Sazan4ek

2024-03-16 19:31 UTC, FilipovskyAlex requested changes

2024-03-16 19:31 UTC, FilipovskyAlex commented on Artisan-HW/app/Console/Commands/ShowConfigKey.php
> +        if($answer === 'Ключ конфигурации не найден') $this->error($answer);
не совсем правильно тут в default это вставлять, лучше проверяй значение из конфига на null

И также не забывай, как хорошая практика, выносить все константные значения в переменные, так как у тебя класс тут, то можно в классовую константу

2024-03-16 19:31 UTC, FilipovskyAlex commented on Artisan-HW/app/Console/Commands/ShowConfigKey.php
> +        else dd($answer);
dd не используем

2024-03-16 19:31 UTC, FilipovskyAlex commented on Artisan-HW/routes/console.php
> +Schedule::call(function (){
данная команда автоматически запускается при artisan schedule:run?

2024-03-16 19:31 UTC, FilipovskyAlex commented on Artisan-HW/routes/console.php
> +})->everyFiveSeconds();
каждые 6 часов

2024-03-16 19:48 UTC, Sazan4ek commented on Artisan-HW/routes/console.php
> +})->everyFiveSeconds();
да, забыл поменять просто :)

2024-03-16 20:42 UTC, Sazan4ek commented on Artisan-HW/app/Console/Commands/ShowConfigKey.php
> +        else dd($answer);
а как вывести значение нормально в консоль, если там может быть массив и при этом чтобы было видно все значения false и true и остальные? пробовал через print_r, но он это не выводит нормально, как я сказал выше

2024-03-16 20:44 UTC, Sazan4ek commented on Artisan-HW/routes/console.php
> +Schedule::call(function (){
да

2024-03-16 20:47 UTC, Sazan4ek commented on Artisan-HW/app/Console/Commands/ShowConfigKey.php
> +        if($answer === 'Ключ конфигурации не найден') $this->error($answer);
Не понял, про какой класс, который можно вынести в константу, идёт речь

2024-03-24 11:10 UTC, FilipovskyAlex commented on Artisan-HW/app/Console/Commands/ShowConfigKey.php
> +        if($answer === 'Ключ конфигурации не найден') $this->error($answer);
'Ключ конфигурации не найден'

2024-03-24 11:10 UTC, FilipovskyAlex commented on Artisan-HW/app/Console/Commands/ShowConfigKey.php
> +        else dd($answer);
echo попробуй

2024-04-06 11:46 UTC, merged