Requests-HW was created
Sazan4ek/Laravel-php pull request #3
Opened 2024-02-16 14:06 UTC by Sazan4ek

2024-02-21 07:15 UTC, FilipovskyAlex requested changes

2024-02-21 07:15 UTC, FilipovskyAlex commented on Requests-HW/app/Rules/TokyoEmployee.php
> +        if($value !== 5)
константные значения не должны использоваться в коде просто так. Даже если учесть, что у тебя будет строго определен id для офиса в токио, то это должно выноситься в константы класса либо в файлы конфигов.

В данном же случае проверять, что это именно токио лучше по имени, то есть здесь нужен запрос модельки офиса по id и проверка его города

2024-02-21 07:15 UTC, FilipovskyAlex commented
Не могу найти 2 задание

2024-02-21 07:23 UTC, FilipovskyAlex requested changes

2024-02-21 07:23 UTC, FilipovskyAlex commented on Requests-HW/app/Http/Controllers/ProductController.php
> +        dd($products);
dd убираем

2024-02-21 07:23 UTC, FilipovskyAlex commented on Requests-HW/app/Http/Controllers/ProductController.php
> +        dd($products);
+ не вижу валидации на этот роут

2024-02-21 09:53 UTC, Sazan4ek commented on Requests-HW/app/Http/Controllers/ProductController.php
> +        dd($products);
Так в ТЗ и не сказано, что валидация должна быть)

2024-03-03 10:57 UTC, FilipovskyAlex commented on Requests-HW/app/Http/Controllers/ProductController.php
> +        dd($products);
ну это подразумевается всякий раз, когда у тебя есть данные, которые вводит пользователь (в данном случае фронтенд - тоже пользователь твоей системы, тебе нужно проверить, что значения, которые он ввел для фильтраций не поломают твою систему и они допустимы)

2024-03-03 10:59 UTC, FilipovskyAlex approved these changes

2024-03-03 10:59 UTC, FilipovskyAlex commented on Requests-HW/app/Http/Requests/ProductFilterRequest.php
> +            'price' => ['nullable', 'integer', 'exists:products,buyPrice'],
цена - это некая граница цены, тут конечно уже неважно, но в целом тут бывает правило от до определенной цены

2024-03-03 11:00 UTC, FilipovskyAlex commented
просто просмотри коменты мои и переведи обратно на меня

2024-03-03 14:32 UTC, merged